# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/an3/SSC/proiect/ALU/ALU.cache/wt [current_project]
set_property parent.project_path D:/an3/SSC/proiect/ALU/ALU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/an3/SSC/proiect/ALU/ALU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/1bitAdder.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/DIV.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/ID.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/IF.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/LU.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/Mux1bitS.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/RegStare.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/Rotate.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/SumSub.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/UC.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/UC_div.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/UC_mul.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/comparator.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/flags.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/inmultitor.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/mux_32.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/registru.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/rezImpartire.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/rezInmultire.vhd
  D:/an3/SSC/proiect/ALU/ALU.srcs/sources_1/new/ALU.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ALU -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ALU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ALU_utilization_synth.rpt -pb ALU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
